include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    dead_code: ignore
    unnecessary_null_comparison: ignore
    deprecated_member_use: ignore
    avoid_web_libraries_in_flutter: ignore
